services:
  web:
    image: hemna6969/wxnow-website:latest
    container_name: aprsd-wxnow-website
    volumes:
      - ./app:/app
      - ./logs:/logs
      - /home/waboring/docker/aprsd-wxnow/app/config:/config
    ports:
      - 4001:80
    restart: unless-stopped
    environment:
      #- FLASK_APP=main.py
      - FLASK_DEBUG=1
        #- 'RUN=flask run --host=0.0.0.0 --port=80'
      - PORT=80
